import React from "react";

type IconProps = {
  name: string;
} & React.SVGProps<SVGSVGElement>;

/**
 * Renders an SVG icon from the spritemap.
 * This component is typed for TypeScript projects.
 *
 * @param {IconProps} props - The component props.
 */
// 2. Type the component with React.FC (Functional Component) and our props type
const Icon: React.FC<IconProps> = ({ name, className, ...rest }) => {
  if (!name) {
    return null;
  }

  // The path to the spritemap generated by the Vite plugin.
  const href = `/__spritemap#sprite-${name}`;

  return (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} {...rest}>
      <use href={href} />
    </svg>
  );
};

export default Icon;
